In [1764]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [1765]:
#carga de archivo csv
df = pd.read_csv('Datos_limpios_chicago.csv')

In [1766]:
#Rellenamos nulos
df=df.fillna(method='bfill')
df=df.fillna(method='ffill')

C:\Users\yack_\AppData\Local\Temp\ipykernel_22148\2881413276.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df=df.fillna(method='bfill')
C:\Users\yack_\AppData\Local\Temp\ipykernel_22148\2881413276.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df=df.fillna(method='ffill')


In [1767]:
#Convirtiendo una variable a dicotómica
df['room_type'] = df['room_type'].replace(
    [ 'Private room', 'Shared room'],
    'Hotel room'
)
df['room_type'] = np.where(df['room_type'] == 'Entire home/apt', 1, 0)

#Convirtiendo una variable a dicotómica
df['host_response_time'] = df['host_response_time'].replace([ 'No definido', 'a few days or more', 'within an hour'],'within a few hours')
df['host_response_time'] = np.where(df['host_response_time'] == 'within a day', 1, 0)

HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE

In [1768]:
#Declaramos las varibles dependientes e independientes para la regresión Logística
Vars_Indep=df[['number_of_reviews', 'price', 'beds']]
var_Dep=df['host_is_superhost']

In [1769]:
#Redefinimos las varibles
X = Vars_Indep
y = var_Dep

In [1770]:
#Dividimos el conjunto de datos en la parte de entrenamiento80 y prueba20:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [1771]:
#Se escalan todos los datos
escalar = StandardScaler()

In [1772]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueba, utilizaremos
X_train1 = escalar.fit_transform(X_train)
X_test1 = escalar.transform(X_test)

In [1773]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [1774]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1775]:
#Relizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 'f', 't', ..., 'f', 'f', 'f'], shape=(2481,), dtype=object)

In [1776]:
#Verifico la matriz de Confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

Matriz de Confusión
[[1120  234]
 [ 667  460]]


In [1777]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average='binary', pos_label='t')
print('Precisión del modelo cierto en HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE')
print(precision)

precision = precision_score(y_test, y_pred, average='binary', pos_label='f')
print('Precisión del modelo falso en HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE')
print(precision)

Precisión del modelo cierto en HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE
0.6628242074927954
Precisión del modelo falso en HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE
0.6267487409065473


In [1778]:
#Calculado la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo en HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE')
print(exactitud)

Exactitud del modelo en HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE
0.6368399838774688


In [1779]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='t')
print('Sensibilidad del modelo cierto en HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE')
print(sensibilidad)

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='f')
print('Sensibilidad del modelo falso en HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE')
print(sensibilidad)

Sensibilidad del modelo cierto en HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE
0.40816326530612246
Sensibilidad del modelo falso en HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE
0.827178729689808


INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE

In [1780]:
#Declaramos las varibles dependientes e independientes para la regresión Logística
Vars_Indep=df[['review_scores_rating', 'price']]
var_Dep=df['instant_bookable']

In [1781]:
#Redefinimos las varibles
X = Vars_Indep
y = var_Dep

In [1782]:
#Dividimos el conjunto de datos en la parte de entrenamiento80 y prueba20:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [1783]:
#Se escalan todos los datos
escalar = StandardScaler()

In [1784]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueba, utilizaremos
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1785]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [1786]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1787]:
#Relizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['f', 't', 'f', ..., 'f', 'f', 'f'], shape=(2481,), dtype=object)

In [1788]:
#Verifico la matriz de Confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

Matriz de Confusión
[[1482  113]
 [ 809   77]]


In [1789]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average='binary', pos_label='t')
print('Precisión del modelo cierto en INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE')
print(precision)

precision = precision_score(y_test, y_pred, average='binary', pos_label='f')
print('Precisión del modelo falso en INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE')
print(precision)

Precisión del modelo cierto en INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE
0.4052631578947368
Precisión del modelo falso en INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE
0.6468790920995199


In [1790]:
#Calculado la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo en INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE')
print(exactitud)

Exactitud del modelo en INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE
0.6283756549778315


In [1791]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='t')
print('Sensibilidad del modelo cierto en INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE')
print(sensibilidad)

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='f')
print('Sensibilidad del modelo falso en INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE')
print(sensibilidad)

Sensibilidad del modelo cierto en INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE
0.08690744920993228
Sensibilidad del modelo falso en INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE
0.929153605015674


3 . HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS

In [1792]:
#Declaramos las varibles dependientes e independientes para la regresión Logística
Vars_Indep=df[['availability_365', 'minimum_nights']]
var_Dep=df['has_availability']

In [1793]:
#Redefinimos las varibles
X = Vars_Indep
y = var_Dep

In [1794]:
#Dividimos el conjunto de datos en la parte de entrenamiento80 y prueba20:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [1795]:
#Se escalan todos los datos
escalar = StandardScaler()

In [1796]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueba, utilizaremos
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1797]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [1798]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1799]:
#Relizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], shape=(2481,), dtype=object)

In [1800]:
#Verifico la matriz de Confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

Matriz de Confusión
[[   0   17]
 [   0 2464]]


In [1801]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average='binary', pos_label='t')
print('Precisión del modelo verdadero en HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS')
print(precision)

precision = precision_score(y_test, y_pred, average='binary', pos_label='f')
print('Precisión del modelo falso en HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS')
print(precision)

Precisión del modelo verdadero en HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS
0.9931479242241031
Precisión del modelo falso en HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS
0.0


c:\Users\yack_\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [1802]:
#Calculado la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo en HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS')
print(exactitud)

Exactitud del modelo en HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS
0.9931479242241031


In [1803]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='t')
print('Sensibilidad del modelo verdadero en HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS')
print(sensibilidad)

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='f')
print('Sensibilidad del modelo falso en HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS')
print(sensibilidad)

Sensibilidad del modelo verdadero en HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS
1.0
Sensibilidad del modelo falso en HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS
0.0


4 . HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT

In [1804]:
df['host_identity_verified'] = df['host_identity_verified'].map({'t': 1, 'f': 0})

In [1805]:
#Declaramos las varibles dependientes e independientes para la regresión Logística
Vars_Indep=df[['host_response_rate', 'host_total_listings_count']]
var_Dep=df['host_identity_verified']

In [1806]:
#Redefinimos las varibles
X = Vars_Indep
y = var_Dep

In [1807]:
#Dividimos el conjunto de datos en la parte de entrenamiento80 y prueba20:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [1808]:
#Se escalan todos los datos
escalar = StandardScaler()

In [1809]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueba, utilizaremos
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1810]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [1811]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1812]:
#Relizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1], shape=(2481,))

In [1813]:
#Verifico la matriz de Confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

Matriz de Confusión
[[   0  238]
 [   0 2243]]


In [1814]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average='binary', pos_label=1)
print('Precisión del modelo verdadero en HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT')
print(precision)

precision = precision_score(y_test, y_pred, average='binary', pos_label=0)
print('Precisión del modelo falso en HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT')
print(precision)

Precisión del modelo verdadero en HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT
0.9040709391374446
Precisión del modelo falso en HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT
0.0


c:\Users\yack_\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [1815]:
#Calculado la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo en HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT')
print(exactitud)

Exactitud del modelo en HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT
0.9040709391374446


In [1816]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=1)
print('Sensibilidad del modelo verdadero en HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT')
print(sensibilidad)

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=0)
print('Sensibilidad del modelo falso en HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT')
print(sensibilidad)

Sensibilidad del modelo verdadero en HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT
1.0
Sensibilidad del modelo falso en HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT
0.0


5 .HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS

In [1817]:
#Declaramos las varibles dependientes e independientes para la regresión Logística
Vars_Indep=df[['review_scores_communication', 'beds']]
var_Dep=df['host_has_profile_pic']

In [1818]:
#Redefinimos las varibles
X = Vars_Indep
y = var_Dep

In [1819]:
#Dividimos el conjunto de datos en la parte de entrenamiento80 y prueba20:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [1820]:
#Se escalan todos los datos
escalar = StandardScaler()

In [1821]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueba, utilizaremos
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1822]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [1823]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1824]:
#Relizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], shape=(2481,), dtype=object)

In [1825]:
#Verifico la matriz de Confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

Matriz de Confusión
[[   0   53]
 [   0 2428]]


In [1826]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average='binary', pos_label='t')
print('Precisión del modelo verdadero en HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS')
print(precision)

precision = precision_score(y_test, y_pred, average='binary', pos_label='f')
print('Precisión del modelo falso en HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS')
print(precision)

Precisión del modelo verdadero en HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS
0.9786376461104394
Precisión del modelo falso en HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS
0.0


c:\Users\yack_\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [1827]:
#Calculado la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo en HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS')
print(exactitud)

Exactitud del modelo en HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS
0.9786376461104394


In [1828]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='t')
print('Sensibilidad del modelo veradero en HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS')
print(sensibilidad)

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='f')
print('Sensibilidad del modelo falso en HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS')
print(sensibilidad)

Sensibilidad del modelo veradero en HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS
1.0
Sensibilidad del modelo falso en HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS
0.0


6 . ROOM_TYPE VS PRICE, BEDROOMS

In [1829]:
#Declaramos las varibles dependientes e independientes para la regresión Logística
Vars_Indep=df[['price', 'bedrooms']]
var_Dep=df['room_type']

In [1830]:
#Redefinimos las varibles
X = Vars_Indep
y = var_Dep

In [1831]:
#Dividimos el conjunto de datos en la parte de entrenamiento80 y prueba20:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [1832]:
#Se escalan todos los datos
escalar = StandardScaler()

In [1833]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueba, utilizaremos
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1834]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [1835]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1836]:
#Relizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1], shape=(2481,))

In [1837]:
#Verifico la matriz de Confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

Matriz de Confusión
[[ 253  303]
 [ 125 1800]]


In [1838]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average='binary', pos_label=1)
print('Precisión del modelo Entire home en ROOM_TYPE VS PRICE, BEDROOMS')
print(precision)

precision = precision_score(y_test, y_pred, average='binary', pos_label=0)
print('Precisión del modelo Private room en ROOM_TYPE VS PRICE, BEDROOMS')
print(precision)

Precisión del modelo Entire home en ROOM_TYPE VS PRICE, BEDROOMS
0.8559201141226819
Precisión del modelo Private room en ROOM_TYPE VS PRICE, BEDROOMS
0.6693121693121693


In [1839]:
#Calculado la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo en ROOM_TYPE VS PRICE, BEDROOMS')
print(exactitud)

Exactitud del modelo en ROOM_TYPE VS PRICE, BEDROOMS
0.8274889157597742


In [1840]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=1)
print('Sensibilidad del modelo Entire home en ROOM_TYPE VS PRICE, BEDROOMS')
print(sensibilidad)

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=0)
print('Sensibilidad del modelo Private room en ROOM_TYPE VS PRICE, BEDROOMS')
print(sensibilidad)

Sensibilidad del modelo Entire home en ROOM_TYPE VS PRICE, BEDROOMS
0.935064935064935
Sensibilidad del modelo Private room en ROOM_TYPE VS PRICE, BEDROOMS
0.4550359712230216


7 .  host_identity_verified VS calculated_host_listings_count, price

In [1841]:
#Declaramos las varibles dependientes e independientes para la regresión Logística
Vars_Indep=df[['calculated_host_listings_count', 'price']]
var_Dep=df['host_identity_verified']

In [1842]:
#Redefinimos las varibles
X = Vars_Indep
y = var_Dep

In [1843]:
#Dividimos el conjunto de datos en la parte de entrenamiento80 y prueba20:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [1844]:
#Se escalan todos los datos
escalar = StandardScaler()

In [1845]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueba, utilizaremos
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1846]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [1847]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1848]:
#Relizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1], shape=(2481,))

In [1849]:
#Verifico la matriz de Confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

Matriz de Confusión
[[   0  231]
 [   0 2250]]


In [1850]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average='binary', pos_label=1)
print('Precisión del modelo verdadero en host_identity_verified VS calculated_host_listings_count, price')
print(precision)

precision = precision_score(y_test, y_pred, average='binary', pos_label=0)
print('Precisión del modelo falso en host_identity_verified VS calculated_host_listings_count, price')
print(precision)

Precisión del modelo verdadero en host_identity_verified VS calculated_host_listings_count, price
0.9068923821039904
Precisión del modelo falso en host_identity_verified VS calculated_host_listings_count, price
0.0


c:\Users\yack_\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [1851]:
#Calculado la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo en host_identity_verified VS calculated_host_listings_count, price')
print(exactitud)

Exactitud del modelo en host_identity_verified VS calculated_host_listings_count, price
0.9068923821039904


In [1852]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=1)
print('Sensibilidad del modelo veradero en host_identity_verified VS calculated_host_listings_count, price')
print(sensibilidad)

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=0)
print('Sensibilidad del modelo falso en host_identity_verified VS calculated_host_listings_count, price')
print(sensibilidad)

Sensibilidad del modelo veradero en host_identity_verified VS calculated_host_listings_count, price
1.0
Sensibilidad del modelo falso en host_identity_verified VS calculated_host_listings_count, price
0.0


8 . has_availability vs review_scores_cleanliness, review_scores_location

In [1853]:
#Declaramos las varibles dependientes e independientes para la regresión Logística
Vars_Indep=df[['review_scores_cleanliness', 'review_scores_location']]
var_Dep=df['has_availability']

In [1854]:
#Redefinimos las varibles
X = Vars_Indep
y = var_Dep

In [1855]:
#Dividimos el conjunto de datos en la parte de entrenamiento80 y prueba20:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [1856]:
#Se escalan todos los datos
escalar = StandardScaler()

In [1857]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueba, utilizaremos
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1858]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [1859]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1860]:
#Relizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], shape=(2481,), dtype=object)

In [1861]:
#Verifico la matriz de Confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

Matriz de Confusión
[[   0    8]
 [   0 2473]]


In [1862]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average='binary', pos_label='t')
print('Precisión del modelo verdadero en has_availability vs review_scores_cleanliness, review_scores_location')
print(precision)

precision = precision_score(y_test, y_pred, average='binary', pos_label='f')
print('Precisión del modelo falso en has_availability vs review_scores_cleanliness, review_scores_location')
print(precision)

Precisión del modelo verdadero en has_availability vs review_scores_cleanliness, review_scores_location
0.9967754937525192
Precisión del modelo falso en has_availability vs review_scores_cleanliness, review_scores_location
0.0


c:\Users\yack_\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [1863]:
#Calculado la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo en has_availability vs review_scores_cleanliness, review_scores_location')
print(exactitud)

Exactitud del modelo en has_availability vs review_scores_cleanliness, review_scores_location
0.9967754937525192


In [1864]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='t')
print('Sensibilidad del modelo verdadero en has_availability vs review_scores_cleanliness, review_scores_location')
print(sensibilidad)

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='f')
print('Sensibilidad del modelo falso en has_availability vs review_scores_cleanliness, review_scores_location')
print(sensibilidad)

Sensibilidad del modelo verdadero en has_availability vs review_scores_cleanliness, review_scores_location
1.0
Sensibilidad del modelo falso en has_availability vs review_scores_cleanliness, review_scores_location
0.0


9 . host_response_rate vs price, number_of_reviews

In [1865]:
#Declaramos las varibles dependientes e independientes para la regresión Logística
Vars_Indep=df[['price', 'number_of_reviews', 'bedrooms']]
var_Dep=df['host_response_time']

In [1866]:
#Redefinimos las varibles
X = Vars_Indep
y = var_Dep

In [1867]:
#Dividimos el conjunto de datos en la parte de entrenamiento80 y prueba20:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [1868]:
#Se escalan todos los datos
escalar = StandardScaler()

In [1869]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueba, utilizaremos
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1870]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [1871]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1872]:
#Relizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(2481,))

In [1873]:
#Verifico la matriz de Confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

Matriz de Confusión
[[2395    0]
 [  86    0]]


In [1874]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average='binary', pos_label=1)
print('Precisión del modelo within a day en host_response_rate vs price, number_of_reviews')
print(precision)

precision = precision_score(y_test, y_pred, average='binary', pos_label=0)
print('Precisión del modelo within an hours en host_response_rate vs price, number_of_reviews')
print(precision)

Precisión del modelo within a day en host_response_rate vs price, number_of_reviews
0.0
Precisión del modelo within an hours en host_response_rate vs price, number_of_reviews
0.9653365578395808


c:\Users\yack_\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [1875]:
#Calculado la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo en host_response_rate vs price, number_of_reviews')
print(exactitud)

Exactitud del modelo en host_response_rate vs price, number_of_reviews
0.9653365578395808


In [1876]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=1)
print('Sensibilidad del modelo whitin a day en host_response_rate vs price, number_of_reviews')
print(sensibilidad)

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=0)
print('Sensibilidad del modelo whitin an hours en host_response_rate vs price, number_of_reviews')
print(sensibilidad)

Sensibilidad del modelo whitin a day en host_response_rate vs price, number_of_reviews
0.0
Sensibilidad del modelo whitin an hours en host_response_rate vs price, number_of_reviews
1.0


10 . host_is_superhost vs room_type, bedrooms

In [1877]:
#Declaramos las varibles dependientes e independientes para la regresión Logística
Vars_Indep=df[['room_type', 'bedrooms']]
var_Dep=df['host_is_superhost']

In [1878]:
#Redefinimos las varibles
X = Vars_Indep
y = var_Dep

In [1879]:
#Dividimos el conjunto de datos en la parte de entrenamiento80 y prueba20:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [1880]:
#Se escalan todos los datos
escalar = StandardScaler()

In [1881]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueba, utilizaremos
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1882]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [1883]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1884]:
#Relizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['f', 'f', 'f', ..., 'f', 'f', 'f'], shape=(2481,), dtype=object)

In [1885]:
#Verifico la matriz de Confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

Matriz de Confusión
[[1207  180]
 [ 920  174]]


In [1886]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average='binary', pos_label='t')
print('Precisión del modelo verdadero en host_is_superhost vs room_type, bedrooms')
print(precision)

precision = precision_score(y_test, y_pred, average='binary', pos_label='f')
print('Precisión del modelo falso en host_is_superhost vs room_type, bedrooms')
print(precision)

Precisión del modelo verdadero en host_is_superhost vs room_type, bedrooms
0.4915254237288136
Precisión del modelo falso en host_is_superhost vs room_type, bedrooms
0.5674659144334744


In [1887]:
#Calculado la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo en host_is_superhost vs room_type, bedrooms')
print(exactitud)

Exactitud del modelo en host_is_superhost vs room_type, bedrooms
0.5566303909713826


In [1888]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='t')
print('Sensibilidad del modelo verdadero en host_is_superhost vs room_type, bedrooms')
print(sensibilidad)

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='f')
print('Sensibilidad del modelo falso en host_is_superhost vs room_type, bedrooms')
print(sensibilidad)

Sensibilidad del modelo verdadero en host_is_superhost vs room_type, bedrooms
0.1590493601462523
Sensibilidad del modelo falso en host_is_superhost vs room_type, bedrooms
0.8702235039653929
