In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
#carga de archivo csv
df = pd.read_csv('listings_limpio_atenas.csv')

In [3]:
#Rellenamos nulos
df=df.fillna(method='bfill')
df=df.fillna(method='ffill')

C:\Users\danyl\AppData\Local\Temp\ipykernel_12772\2881413276.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df=df.fillna(method='bfill')
C:\Users\danyl\AppData\Local\Temp\ipykernel_12772\2881413276.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df=df.fillna(method='ffill')


In [4]:
#Si price tiene símbolos como $ o comas
df['price'] = df['price'].replace('[\$,]', '', regex=True).astype(float)

<>:2: SyntaxWarning: invalid escape sequence '\$'
<>:2: SyntaxWarning: invalid escape sequence '\$'
C:\Users\danyl\AppData\Local\Temp\ipykernel_12772\2362502043.py:2: SyntaxWarning: invalid escape sequence '\$'
  df['price'] = df['price'].replace('[\$,]', '', regex=True).astype(float)


In [5]:
#Convirtiendo una variable a dicotómica
df['room_type'] = df['room_type'].replace(
    [ 'Private room', 'Shared room'],
    'Hotel room'
)
df['room_type'] = np.where(df['room_type'] == 'Entire home/apt', 1, 0)

#Convirtiendo una variable a dicotómica
df['host_response_time'] = df['host_response_time'].replace([ 'No definido', 'a few days or more', 'within an hour'],'within a few hours')
df['host_response_time'] = np.where(df['host_response_time'] == 'within a day', 1, 0)

HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE

In [6]:
#Declaramos las varibles dependientes e independientes para la regresión Logística
Vars_Indep=df[['number_of_reviews', 'price', 'beds']]
var_Dep=df['host_is_superhost']

In [7]:
#Redefinimos las varibles
X = Vars_Indep
y = var_Dep

In [8]:
#Dividimos el conjunto de datos en la parte de entrenamiento80 y prueba20:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [9]:
#Se escalan todos los datos
escalar = StandardScaler()

In [10]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueba, utilizaremos
X_train1 = escalar.fit_transform(X_train)
X_test1 = escalar.transform(X_test)

In [11]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [12]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [13]:
#Relizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['f', 'f', 'f', ..., 'f', 't', 'f'], shape=(4242,), dtype=object)

In [14]:
#Verifico la matriz de Confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

Matriz de Confusión
[[2388  181]
 [1386  287]]


In [15]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average='binary', pos_label='t')
print('Precisión del modelo cierto en HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE')
print(precision)

precision = precision_score(y_test, y_pred, average='binary', pos_label='f')
print('Precisión del modelo falso en HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE')
print(precision)

Precisión del modelo cierto en HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE
0.6132478632478633
Precisión del modelo falso en HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE
0.6327503974562798


In [16]:
#Calculado la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo en HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE')
print(exactitud)

Exactitud del modelo en HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE
0.6305987741631306


In [17]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='t')
print('Sensibilidad del modelo cierto en HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE')
print(sensibilidad)

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='f')
print('Sensibilidad del modelo falso en HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE')
print(sensibilidad)

Sensibilidad del modelo cierto en HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE
0.17154811715481172
Sensibilidad del modelo falso en HOST_IS_SUPERHOST VS NUMBER_OF_REVIEWS, BEDS, PRICE
0.9295445698715453


INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE

In [18]:
#Declaramos las varibles dependientes e independientes para la regresión Logística
Vars_Indep=df[['review_scores_rating', 'price']]
var_Dep=df['instant_bookable']

In [19]:
#Redefinimos las varibles
X = Vars_Indep
y = var_Dep

In [20]:
#Dividimos el conjunto de datos en la parte de entrenamiento80 y prueba20:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [21]:
#Se escalan todos los datos
escalar = StandardScaler()

In [22]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueba, utilizaremos
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [23]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [24]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [25]:
#Relizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], shape=(4242,), dtype=object)

In [26]:
#Verifico la matriz de Confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

Matriz de Confusión
[[   0 1449]
 [   0 2793]]


In [27]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average='binary', pos_label='t')
print('Precisión del modelo cierto en INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE')
print(precision)

precision = precision_score(y_test, y_pred, average='binary', pos_label='f')
print('Precisión del modelo falso en INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE')
print(precision)

Precisión del modelo cierto en INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE
0.6584158415841584
Precisión del modelo falso en INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE
0.0


c:\Users\danyl\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [28]:
#Calculado la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo en INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE')
print(exactitud)

Exactitud del modelo en INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE
0.6584158415841584


In [29]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='t')
print('Sensibilidad del modelo cierto en INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE')
print(sensibilidad)

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='f')
print('Sensibilidad del modelo falso en INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE')
print(sensibilidad)

Sensibilidad del modelo cierto en INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE
1.0
Sensibilidad del modelo falso en INSTANT_BOOKABLE VS REVIEWS_SCORES_RATING, PRICE
0.0


3 . HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS

In [30]:
#Declaramos las varibles dependientes e independientes para la regresión Logística
Vars_Indep=df[['availability_365', 'minimum_nights']]
var_Dep=df['has_availability']

In [31]:
#Redefinimos las varibles
X = Vars_Indep
y = var_Dep

In [32]:
#Dividimos el conjunto de datos en la parte de entrenamiento80 y prueba20:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [33]:
#Se escalan todos los datos
escalar = StandardScaler()

In [34]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueba, utilizaremos
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [35]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [36]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [37]:
#Relizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], shape=(4242,), dtype=object)

In [38]:
#Verifico la matriz de Confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

Matriz de Confusión
[[   0   18]
 [   0 4224]]


In [39]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average='binary', pos_label='t')
print('Precisión del modelo verdadero en HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS')
print(precision)

precision = precision_score(y_test, y_pred, average='binary', pos_label='f')
print('Precisión del modelo falso en HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS')
print(precision)

Precisión del modelo verdadero en HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS
0.9957567185289957
Precisión del modelo falso en HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS
0.0


c:\Users\danyl\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [40]:
#Calculado la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo en HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS')
print(exactitud)

Exactitud del modelo en HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS
0.9957567185289957


In [41]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='t')
print('Sensibilidad del modelo verdadero en HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS')
print(sensibilidad)

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='f')
print('Sensibilidad del modelo falso en HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS')
print(sensibilidad)

Sensibilidad del modelo verdadero en HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS
1.0
Sensibilidad del modelo falso en HAS_AVAILABILITY VS AVAILABILITY_365, MINIMUM_NIGHTS
0.0


4 . HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT

In [42]:
df['host_identity_verified'] = df['host_identity_verified'].map({'t': 1, 'f': 0})

In [43]:
#Declaramos las varibles dependientes e independientes para la regresión Logística
Vars_Indep=df[['host_response_rate', 'host_total_listings_count']]
var_Dep=df['host_identity_verified']

In [ ]:
print(df['host_response_rate'].dtype)

In [44]:
#Redefinimos las varibles
X = Vars_Indep
y = var_Dep

In [45]:
#Dividimos el conjunto de datos en la parte de entrenamiento80 y prueba20:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [46]:
#Se escalan todos los datos
escalar = StandardScaler()

In [47]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueba, utilizaremos
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

ValueError: could not convert string to float: '89.0%'

In [ ]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [ ]:
#Relizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1], shape=(2481,))

In [ ]:
#Verifico la matriz de Confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

Matriz de Confusión
[[   0  238]
 [   0 2243]]


In [ ]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average='binary', pos_label=1)
print('Precisión del modelo verdadero en HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT')
print(precision)

precision = precision_score(y_test, y_pred, average='binary', pos_label=0)
print('Precisión del modelo falso en HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT')
print(precision)

Precisión del modelo verdadero en HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT
0.9040709391374446
Precisión del modelo falso en HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT
0.0


c:\Users\yack_\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
#Calculado la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo en HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT')
print(exactitud)

Exactitud del modelo en HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT
0.9040709391374446


In [ ]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=1)
print('Sensibilidad del modelo verdadero en HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT')
print(sensibilidad)

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=0)
print('Sensibilidad del modelo falso en HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT')
print(sensibilidad)

Sensibilidad del modelo verdadero en HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT
1.0
Sensibilidad del modelo falso en HOST_IDENTITY_VERIFIED VS HOST_RESPONSE_RATE, HOST_TOTAL_LISTING_COUNT
0.0


5 .HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS

In [ ]:
#Declaramos las varibles dependientes e independientes para la regresión Logística
Vars_Indep=df[['review_scores_communication', 'beds']]
var_Dep=df['host_has_profile_pic']

In [ ]:
#Redefinimos las varibles
X = Vars_Indep
y = var_Dep

In [ ]:
#Dividimos el conjunto de datos en la parte de entrenamiento80 y prueba20:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [ ]:
#Se escalan todos los datos
escalar = StandardScaler()

In [ ]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueba, utilizaremos
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [ ]:
#Relizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], shape=(2481,), dtype=object)

In [ ]:
#Verifico la matriz de Confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

Matriz de Confusión
[[   0   53]
 [   0 2428]]


In [ ]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average='binary', pos_label='t')
print('Precisión del modelo verdadero en HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS')
print(precision)

precision = precision_score(y_test, y_pred, average='binary', pos_label='f')
print('Precisión del modelo falso en HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS')
print(precision)

Precisión del modelo verdadero en HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS
0.9786376461104394
Precisión del modelo falso en HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS
0.0


c:\Users\yack_\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
#Calculado la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo en HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS')
print(exactitud)

Exactitud del modelo en HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS
0.9786376461104394


In [ ]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='t')
print('Sensibilidad del modelo veradero en HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS')
print(sensibilidad)

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='f')
print('Sensibilidad del modelo falso en HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS')
print(sensibilidad)

Sensibilidad del modelo veradero en HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS
1.0
Sensibilidad del modelo falso en HOST_HAS_PROFILE_PIC VS REVIEW_SCORES_COMUNICATION, BEDS
0.0


6 . ROOM_TYPE VS PRICE, BEDROOMS

In [ ]:
#Declaramos las varibles dependientes e independientes para la regresión Logística
Vars_Indep=df[['price', 'bedrooms']]
var_Dep=df['room_type']

In [ ]:
#Redefinimos las varibles
X = Vars_Indep
y = var_Dep

In [ ]:
#Dividimos el conjunto de datos en la parte de entrenamiento80 y prueba20:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [ ]:
#Se escalan todos los datos
escalar = StandardScaler()

In [ ]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueba, utilizaremos
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [ ]:
#Relizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1], shape=(2481,))

In [ ]:
#Verifico la matriz de Confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

Matriz de Confusión
[[ 253  303]
 [ 125 1800]]


In [ ]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average='binary', pos_label=1)
print('Precisión del modelo Entire home en ROOM_TYPE VS PRICE, BEDROOMS')
print(precision)

precision = precision_score(y_test, y_pred, average='binary', pos_label=0)
print('Precisión del modelo Private room en ROOM_TYPE VS PRICE, BEDROOMS')
print(precision)

Precisión del modelo Entire home en ROOM_TYPE VS PRICE, BEDROOMS
0.8559201141226819
Precisión del modelo Private room en ROOM_TYPE VS PRICE, BEDROOMS
0.6693121693121693


In [ ]:
#Calculado la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo en ROOM_TYPE VS PRICE, BEDROOMS')
print(exactitud)

Exactitud del modelo en ROOM_TYPE VS PRICE, BEDROOMS
0.8274889157597742


In [ ]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=1)
print('Sensibilidad del modelo Entire home en ROOM_TYPE VS PRICE, BEDROOMS')
print(sensibilidad)

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=0)
print('Sensibilidad del modelo Private room en ROOM_TYPE VS PRICE, BEDROOMS')
print(sensibilidad)

Sensibilidad del modelo Entire home en ROOM_TYPE VS PRICE, BEDROOMS
0.935064935064935
Sensibilidad del modelo Private room en ROOM_TYPE VS PRICE, BEDROOMS
0.4550359712230216


7 .  host_identity_verified VS calculated_host_listings_count, price

In [ ]:
#Declaramos las varibles dependientes e independientes para la regresión Logística
Vars_Indep=df[['calculated_host_listings_count', 'price']]
var_Dep=df['host_identity_verified']

In [ ]:
#Redefinimos las varibles
X = Vars_Indep
y = var_Dep

In [ ]:
#Dividimos el conjunto de datos en la parte de entrenamiento80 y prueba20:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [ ]:
#Se escalan todos los datos
escalar = StandardScaler()

In [ ]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueba, utilizaremos
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [ ]:
#Relizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1], shape=(2481,))

In [ ]:
#Verifico la matriz de Confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

Matriz de Confusión
[[   0  231]
 [   0 2250]]


In [ ]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average='binary', pos_label=1)
print('Precisión del modelo verdadero en host_identity_verified VS calculated_host_listings_count, price')
print(precision)

precision = precision_score(y_test, y_pred, average='binary', pos_label=0)
print('Precisión del modelo falso en host_identity_verified VS calculated_host_listings_count, price')
print(precision)

Precisión del modelo verdadero en host_identity_verified VS calculated_host_listings_count, price
0.9068923821039904
Precisión del modelo falso en host_identity_verified VS calculated_host_listings_count, price
0.0


c:\Users\yack_\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
#Calculado la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo en host_identity_verified VS calculated_host_listings_count, price')
print(exactitud)

Exactitud del modelo en host_identity_verified VS calculated_host_listings_count, price
0.9068923821039904


In [ ]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=1)
print('Sensibilidad del modelo veradero en host_identity_verified VS calculated_host_listings_count, price')
print(sensibilidad)

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=0)
print('Sensibilidad del modelo falso en host_identity_verified VS calculated_host_listings_count, price')
print(sensibilidad)

Sensibilidad del modelo veradero en host_identity_verified VS calculated_host_listings_count, price
1.0
Sensibilidad del modelo falso en host_identity_verified VS calculated_host_listings_count, price
0.0


8 . has_availability vs review_scores_cleanliness, review_scores_location

In [ ]:
#Declaramos las varibles dependientes e independientes para la regresión Logística
Vars_Indep=df[['review_scores_cleanliness', 'review_scores_location']]
var_Dep=df['has_availability']

In [ ]:
#Redefinimos las varibles
X = Vars_Indep
y = var_Dep

In [ ]:
#Dividimos el conjunto de datos en la parte de entrenamiento80 y prueba20:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [ ]:
#Se escalan todos los datos
escalar = StandardScaler()

In [ ]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueba, utilizaremos
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [ ]:
#Relizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], shape=(2481,), dtype=object)

In [ ]:
#Verifico la matriz de Confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

Matriz de Confusión
[[   0    8]
 [   0 2473]]


In [ ]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average='binary', pos_label='t')
print('Precisión del modelo verdadero en has_availability vs review_scores_cleanliness, review_scores_location')
print(precision)

precision = precision_score(y_test, y_pred, average='binary', pos_label='f')
print('Precisión del modelo falso en has_availability vs review_scores_cleanliness, review_scores_location')
print(precision)

Precisión del modelo verdadero en has_availability vs review_scores_cleanliness, review_scores_location
0.9967754937525192
Precisión del modelo falso en has_availability vs review_scores_cleanliness, review_scores_location
0.0


c:\Users\yack_\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
#Calculado la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo en has_availability vs review_scores_cleanliness, review_scores_location')
print(exactitud)

Exactitud del modelo en has_availability vs review_scores_cleanliness, review_scores_location
0.9967754937525192


In [ ]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='t')
print('Sensibilidad del modelo verdadero en has_availability vs review_scores_cleanliness, review_scores_location')
print(sensibilidad)

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='f')
print('Sensibilidad del modelo falso en has_availability vs review_scores_cleanliness, review_scores_location')
print(sensibilidad)

Sensibilidad del modelo verdadero en has_availability vs review_scores_cleanliness, review_scores_location
1.0
Sensibilidad del modelo falso en has_availability vs review_scores_cleanliness, review_scores_location
0.0


9 . host_response_rate vs price, number_of_reviews

In [ ]:
#Declaramos las varibles dependientes e independientes para la regresión Logística
Vars_Indep=df[['price', 'number_of_reviews', 'bedrooms']]
var_Dep=df['host_response_time']

In [ ]:
#Redefinimos las varibles
X = Vars_Indep
y = var_Dep

In [ ]:
#Dividimos el conjunto de datos en la parte de entrenamiento80 y prueba20:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [ ]:
#Se escalan todos los datos
escalar = StandardScaler()

In [ ]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueba, utilizaremos
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [ ]:
#Relizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(2481,))

In [ ]:
#Verifico la matriz de Confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

Matriz de Confusión
[[2395    0]
 [  86    0]]


In [ ]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average='binary', pos_label=1)
print('Precisión del modelo within a day en host_response_rate vs price, number_of_reviews')
print(precision)

precision = precision_score(y_test, y_pred, average='binary', pos_label=0)
print('Precisión del modelo within an hours en host_response_rate vs price, number_of_reviews')
print(precision)

Precisión del modelo within a day en host_response_rate vs price, number_of_reviews
0.0
Precisión del modelo within an hours en host_response_rate vs price, number_of_reviews
0.9653365578395808


c:\Users\yack_\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
#Calculado la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo en host_response_rate vs price, number_of_reviews')
print(exactitud)

Exactitud del modelo en host_response_rate vs price, number_of_reviews
0.9653365578395808


In [ ]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=1)
print('Sensibilidad del modelo whitin a day en host_response_rate vs price, number_of_reviews')
print(sensibilidad)

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=0)
print('Sensibilidad del modelo whitin an hours en host_response_rate vs price, number_of_reviews')
print(sensibilidad)

Sensibilidad del modelo whitin a day en host_response_rate vs price, number_of_reviews
0.0
Sensibilidad del modelo whitin an hours en host_response_rate vs price, number_of_reviews
1.0


10 . host_is_superhost vs room_type, bedrooms

In [ ]:
#Declaramos las varibles dependientes e independientes para la regresión Logística
Vars_Indep=df[['room_type', 'bedrooms']]
var_Dep=df['host_is_superhost']

In [ ]:
#Redefinimos las varibles
X = Vars_Indep
y = var_Dep

In [ ]:
#Dividimos el conjunto de datos en la parte de entrenamiento80 y prueba20:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [ ]:
#Se escalan todos los datos
escalar = StandardScaler()

In [ ]:
#Para realizar el escalamiento de las varibles "X" tanto de entrenamiento como de prueba, utilizaremos
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [ ]:
#Relizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['f', 'f', 'f', ..., 'f', 'f', 'f'], shape=(2481,), dtype=object)

In [ ]:
#Verifico la matriz de Confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

Matriz de Confusión
[[1207  180]
 [ 920  174]]


In [ ]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average='binary', pos_label='t')
print('Precisión del modelo verdadero en host_is_superhost vs room_type, bedrooms')
print(precision)

precision = precision_score(y_test, y_pred, average='binary', pos_label='f')
print('Precisión del modelo falso en host_is_superhost vs room_type, bedrooms')
print(precision)

Precisión del modelo verdadero en host_is_superhost vs room_type, bedrooms
0.4915254237288136
Precisión del modelo falso en host_is_superhost vs room_type, bedrooms
0.5674659144334744


In [ ]:
#Calculado la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo en host_is_superhost vs room_type, bedrooms')
print(exactitud)

Exactitud del modelo en host_is_superhost vs room_type, bedrooms
0.5566303909713826


In [ ]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='t')
print('Sensibilidad del modelo verdadero en host_is_superhost vs room_type, bedrooms')
print(sensibilidad)

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='f')
print('Sensibilidad del modelo falso en host_is_superhost vs room_type, bedrooms')
print(sensibilidad)

Sensibilidad del modelo verdadero en host_is_superhost vs room_type, bedrooms
0.1590493601462523
Sensibilidad del modelo falso en host_is_superhost vs room_type, bedrooms
0.8702235039653929
